### ISSUE TITLE
Failed to build when webpack alias for asset is an array of paths instead of a single path

### ISSUE THREAD

**Issue by Rush** [webdiscus/pug-loader#10]
See my full repro here: https://github.com/Rush/webdiscus-repro and run `npm run reproduce`.

Or to reproduce by hand, setup the resolve alias as a list of paths, instead of a single path
```
resolve: {
  alias: {
    assets: [ assetPath1, assetPath2 ]
```

and then require the asset from `pug`
```
Module not found: Error: Can't resolve '/code/webdiscus-pug-node-example/assets,/code/webdiscus-pug-node-example/assets2/fonts/ibm-plex-sans-v7-latin-regular.woff2' in '/code/webdiscus-pug-node-example/server/views'
```
Requiring same asset from JS/TS works fine via:
```
require('assets/fonts/ibm-plex-sans-v7-latin-regular.woff2');
```

**Comment by Rush** [comment]
Thanks for adding it to the "in development" milestone. :) I hope I will not have to wait for long as I'm slightly blocked, but not too worry too much :)

**Comment by webdiscus** [comment]
hallo @Rush 

thank you for very important issue. I have enhanced the resolving of alias for array.

You can see possible usage cases in the [fixture](https://github.com/webdiscus/pug-loader/blob/master/test/cases/require-alias-array-compile/src/index.pug) and [resolve.alias](https://github.com/webdiscus/pug-loader/blob/master/test/cases/require-alias-array-compile/webpack.config.js) for `compile` method.

> ### ⚠️ Limitation for `compile` method and alias as an array
> 
> Usage of a variable in request don't work if alias is an array:
> ```js
> resolve: {
>   alias: {
>      Images: ['/path_1/', '/path_2/'],     
>   }
> }
> ```
> ```pug
> - var basename = 'logo';
> img(src=require('Images/' + basename + '-c1.jpeg')) <-- does not work
> 
> img(src=require('Images/logo.jpeg')) <-- works
> ```

This is limitation of webpack compiler self, webpack don't recognize an asset request contained a variable. But the webpack resolver resolve this assets correct. This limitation does not affect the `render` and `html` methods.

New version is `1.7.1`

**Comment by Rush** [comment]
Awesome! THe workaround for not using variables in the require expression is simply to prepare utility data structures. Such as:
```ts
- const statusIcons = { draft: require('images/status/draft.png'), reject: require('images/status/reject.png'), review: require('images/status/review.png'), approve: require('images/status/review.png') };
```

**Comment by Rush** [comment]
Fixed, works great now. Thank you!
