### ISSUE TITLE
How to use it with tailwindcss and server side rendering?

### ISSUE THREAD

**Issue by Bessonov** [webdiscus/pug-loader#13]
Thanks for great loader!

## What would I like to achieve

Following template:
```pug
// index.pug
doctype html
html(lang="en")
  head
    link(rel='stylesheet', href='tailwind-generated.css')
  body
    h1.bg-red-500 #{myVar}
```

and following backend function:
```typescript
// index.ts
import indexTpl from './index.pug'

function index(): string {
	return indexTpl({
		myVar: 'some value got from elsewhere'
	})
}
```

should produce html string and generate following file with [tailwindcss' jit](https://tailwindcss.com/blog/just-in-time-the-next-generation-of-tailwind-css):
```css
/* tailwind-generated.css */
.bg-red-500 {
    --tw-bg-opacity: 1;
    background-color: rgb(239 68 68 / var(--tw-bg-opacity));
}
```

## What I already got

ATM I get the value `myVar` into generated html-string, but I fail at generating and including the css file.

Any idea how to achieve that? I can create a small repro, if needed.

**Comment by webdiscus** [comment]
Hello @Bessonov,

I have no experience with tailwind css.
Can you please create a repo with your usage case, including expected result?

**Comment by webdiscus** [comment]
The pug-loader is designed for Webpack only and can't be used for server side rendering.

**Comment by Bessonov** [comment]
Thank you very mich for your quick response!

I think I was wrong. Probably, the question isn't related to `pug-loader` at all. Usually, tailwindcss' jit use html (or jsx/tsx) to extract class names and then generate appropriate css definitions (see [working frontend example](https://github.com/Bessonov/monorepo-starter/blob/main/packages/frontend/tailwind.config.js#L3)). Then they are injected [through webpack](https://github.com/Bessonov/monorepo-starter/blob/main/packages/frontend/webpack.config.js#L91).

Instead, `pug-loader` creates a callable function from pug files. Because of control structures it's "too late" at this point. Therefore classes should be extracted directly from pug files.

If I don't miss something, this question can be closed.

Anyway, you can find the repro here: https://github.com/Bessonov/pug-loader-tailwindcss-repro
With `npm start` you see the generated result, but I wasn't able to generate `tailwind-generated.css` file with webpack. Expected output can be generated with `npm run simulate-tailwindcss`.

**Comment by Bessonov** [comment]
Well, I got one step further and now I have `pug-loader`/`pug-plugin` related question/issue. With [this change](https://github.com/Bessonov/pug-loader-tailwindcss-repro/commit/23a9be476db455b3da979e36437beee9641c4d6c) I get at least generated and expected css output. But it's inlined instead of separate file:
```html
<!DOCTYPE html><html lang="en"><head><link rel="stylesheet" href="{&quot;default&quot;:[[&quot;./src/main.css&quot;,&quot;/*\n! tailwindcss v3.0.23
[...]
.bg-red-500 {\n  --tw-bg-opacity: 1;\n  background-color: rgb(239 68 68 / var(--tw-bg-opacity));\n}\nbody {\n    background-color: aqua;\n}&quot;,&quot;&quot;]]}"></head><body><h1 class="bg-red-500">some value got from elsewhere</h1></body></html>
```

If I use `mini-css-extract-plugin` (which I shouldn't), then it creates generated file, but produces empty webpack chunk and following html output:
```html
<!DOCTYPE html><html lang="en"><head><link rel="stylesheet" href="{}"></head><body><h1 class="bg-red-500">some value got from elsewhere</h1></body></html>
```

Any idea?

**Comment by webdiscus** [comment]
Thank you for the feedback.
I can reproduce the problem. I try to find a solution.

**Comment by Bessonov** [comment]
Forgot to mention that the issue isn't related to tailwindcss/postcss-loader. You can remove `postcss-loader` and `@tailwind` definitions in `main.css`.

**Comment by Bessonov** [comment]
I think I got a solution. I must confirm it and then I will post it here.

**Comment by Bessonov** [comment]
So, after trying multiple things [I got it working](https://github.com/Bessonov/pug-loader-tailwindcss-repro/commit/319f480ede5dd03deac35923e5efa23fd0338c59#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR47-R48) :tada: 

The change is self explanatory, but in the core I replaced `css-loader` with webpack 5 asset configuration and add `postcss-loader`:

```javascript
			{
				test: /\.pug$/,
				loader: '@webdiscus/pug-loader',
			},
			{
				test: /\.css$/,
				type: 'asset/resource',
				use: 'postcss-loader',
			},
```

After that I got:
```html
<!DOCTYPE html><html lang="en"><head><link rel="stylesheet" href="/e9ee15a03b9e6daca3ad.css"></head><body><h1 class="bg-red-500">some value got from elsewhere</h1></body></html>
```
```bash
$ ls dist/
e9ee15a03b9e6daca3ad.css  index.js
```
```css
/* dist/e9ee15a03b9e6daca3ad.css */
/*
! tailwindcss v3.0.23 | MIT License | https://tailwindcss.com
*//*
[...]
.bg-red-500 {
  --tw-bg-opacity: 1;
  background-color: rgb(239 68 68 / var(--tw-bg-opacity));
}
body {
    background-color: aqua;
}
```
:+1:

**Comment by webdiscus** [comment]
cool :-)

The pug-plugin can extract css from required styles in pug, but self pug must be defined in entry-point.
In your case the css is required from nested require, like require(pug(require(css))), then so deep require(css) is not work.

**Comment by andrejcesen** [comment]
> So, after trying multiple things [I got it working](https://github.com/Bessonov/pug-loader-tailwindcss-repro/commit/319f480ede5dd03deac35923e5efa23fd0338c59#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR47-R48) 🎉

Great work @Bessonov! Curious to check out your solution, but the link seems to be down. Any chance to resurrect it?

**Comment by Bessonov** [comment]
@andrejcesen Oh, dear, I have two news for you. A good one and a bad one. The bad one, I have deleted the repo. The good one, I found a copy in my backups and I pushed it again 👍

**Comment by webdiscus** [comment]
@Bessonov 

I see, you have used the pug-plugin `v1.5.0`. Today actual version of  [pug-plugin](https://github.com/webdiscus/pug-plugin) is `v4.9.3` and it can much more.
For example, using new version the entry point is a Pug file and all source scripts and styles can be loaded directly in Pug via `link` and `script` tags:

```pug
link(href=require('./style.scss') rel='stylesheet')
script(src=require('./main.ts') defer='defer')
```

All source resource will be processed via Webpack and generated HTML contains  hashed output CSS and JS filenames:
```html
<link href="/assets/css/style.05e4dd86.css" rel="stylesheet">
<script src="/assets/js/main.f4b855d8.js" defer="defer"></script>
```

Add  to Webpack entry a Pug template:
```js
const PugPlugin = require('pug-plugin');
module.exports = {
  entry: {
    // define your Pug files here
    index: './src/views/home/index.pug',  // output dist/index.html
    'route/to/page': './src/views/page/index.pug', // output dist/route/to/page.html
  },
  plugins: [
    new PugPlugin(), // rendering of Pug files defined in Webpack entry
  ],
  module: {
    rules: [
      {
        test: /.pug$/,
        loader: PugPlugin.loader, // Pug loader
      },
      // ... loaders for styles, TS, etc.
    ],
  },
};
```

You can use  a Pug template as any `partial` in JS (e.g. in your `main.ts` loaded via `script` tag In Pug), but this partial should not contains a `link` or `script` tags.
