### ISSUE TITLE
Loading wrong file on file changes

### ISSUE THREAD

**Issue by Rush** [webdiscus/pug-loader#2]
First time build seems to run fine, but on file changes a wrong file seems to be recompiled giving me cryptic angular errors
```
ERROR in src/app/components/manage-page.component.pug:1:4603 - error TS2339: Property 'editorLimit' does not exist on type 'ManagePageComponent'.

1 <div class="editor" #editorDiv [class.full]="hideUI" [class.has-bottom]="showSequence" preventTouch><editor-view [class.ha
```
and then the code shown actually concerns a different file altogether.

**Comment by webdiscus** [comment]
> First time build seems to run fine, but on file changes a wrong file seems to be recompiled giving me cryptic angular errors
> 
> ```
> ERROR in src/app/components/manage-page.component.pug:1:4603 - error TS2339: Property 'editorLimit' does not exist on type 'ManagePageComponent'.
> 
> 1 <div class="editor" #editorDiv [class.full]="hideUI" [class.has-bottom]="showSequence" preventTouch><editor-view [class.ha
> ```
> 
> and then the code shown actually concerns a different file altogether.

Can you please show the code snippet with issue in pug file?
Before analyzing the error, I must be able to reproduce it.

**Comment by webdiscus** [comment]
> First time build seems to run fine, but on file changes a wrong file seems to be recompiled giving me cryptic angular errors
> 
> ```
> ERROR in src/app/components/manage-page.component.pug:1:4603 - error TS2339: Property 'editorLimit' does not exist on type 'ManagePageComponent'.
> 
> 1 <div class="editor" #editorDiv [class.full]="hideUI" [class.has-bottom]="showSequence" preventTouch><editor-view [class.ha
> ```
> 
> and then the code shown actually concerns a different file altogether.

Exact the error TS2339 can I reproduce local if in template is used a angular variable not defined (or private
) property/method in a Component Class.

For example:

app.component.ts
```js
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  styleUrls: ['./app.component.css'],
  templateUrl: './app.component.pug',
})
export class AppComponent {
  myCssClass = 'my-css-class';
}
```

app.component.pug
```pug
#myDiv([class]="myCssClass") some text...
```

This work, but if delete in the property `myCssClass ` in the class `AppComponent` then appear this error `TS2339 `.

Perhaps, you should check whether the property `editorLimit` exists in the class `ManagePageComponent`.
Without a code snippet I can't reproduce your problem.

**Comment by Rush** [comment]
Issue no longer  happening with the latest version and with the `html` mode.
