### ISSUE TITLE
Windows only: Invalid path when using alias

### ISSUE THREAD

**Issue by alterastro** [webdiscus/pug-loader#3]
File paths are not handled correctly when using the alias in `include` and `extends`.
The path specified in the alias is always glued to the path to the current template file.

In the case of `extends`, I get `D:\\projects\\new-app\\src\\pages\\main\\D:\\projects\\new-app\\src\\layouts\\default\\default.pug`
And in the case of `include` - `D:\\projects\\new-app\\src\\layouts\\default\\D:\\projects\\UI\\src\\components\\XApp\\XApp.pug`

In this case, the correct values for the alias are displayed in the console:

```
Exo path: D:/projects/UI/src/components
Layouts path: D:\projects\new-app\src\layouts
```

The following aliases have been added to the webpack config:

```
alias: {
  UI: 'D:/projects/UI/src/components',
  Layouts: path.resolve('src', 'layouts'),
},
```

My project uses the following structure:

```
src/
├── ...
│
├── layouts/
│   ├── default/
│   │   ├── ...
│   │   └── default.pug
│   └── ...
│
├── pages/
│   ├── main/
│   │   ├── ....
│   │   └── main.pug
│   └── ...
│
└── ...
```

Layout code:

```
- var head = {}

block variables

include ~UI/XApp/XApp

doctype html
html
  head
    meta(charset="UTF-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    meta(http-equiv="X-UA-Compatible" content="ie=edge")

    block head
      title.
        #{head.title || 'Default title'} - My Webpage
  body
    +x-app
      block content
```

Page code:

```
extends ~Layouts/default/default

block variables
  -
    var head = {
      title: 'Main page'
    }

block content
  h1 Hellow pug!
```

**Comment by webdiscus** [comment]
Hello @alterastro,

can you please run the tests from the repo directory:
```
npm run test
```
Whether all tests will be passed on your system?

See the [test alias in extends](https://github.com/webdiscus/pug-loader/tree/master/test/cases/extends-alias).
See the [test alias in include](https://github.com/webdiscus/pug-loader/tree/master/test/cases/include-alias).
See the [test alias in require](https://github.com/webdiscus/pug-loader/tree/master/test/cases/require-alias).

All tests are passed on:
- Ubuntu 18 LTS
- Webpack 5.64.3
- Node.js 12, 14, 16

P.S. I can't test it under Windows, sorry. But I want to locate the problem.

**Comment by webdiscus** [comment]
Hello @alterastro,

I found the problem. It has nothing to do with this pug-loader and aliases.

### The issue in pug compiler on Windows
To a filename adds at begin the directory of the source template.
For example:
- source directory: `D:/projects/new-app/src/pages/main/`
 - include a template in pug:
   ```pug
    include D:/projects/new-app/src/layouts/default/default.pug
    ```
The pug compiler translate the file
`include D:/projects/new-app/src/layouts/default/default.pug` \
 into \
`include D:/projects/new-app/src/pages/main/D:/projects/new-app/src/layouts/default/default.pug`

Also, pug compiler do: `source directory` + `included file`.

### Why?
The fixed rule of file naming in pug: an absolute filename **MUST** begin exact with `/`.\
Otherwise will be added at begin of a filename the `source directory`.

The concrete place of issue/feature in source code of pug is [in this file, line 78](https://github.com/pugjs/pug/blob/6cca8f76befe7285eead0416ba4e2dbba825ab65/packages/pug-load/index.js#L78):

```js
load.resolve = function resolve(filename, source, options) {
 // ...
  filename = path.join(
    filename[0] === '/' ? options.basedir : path.dirname(source.trim()), // <==== HERE is the problem
    filename
  );

  return filename;
};
```

## Solution
Adds to an absolute filename at begin the `/`.
For example:
```
alias: {
  UI: '/D:/projects/UI/src/components',
  Layouts: '/' + path.resolve('src', 'layouts'),
},
```

**Comment by alterastro** [comment]
> Hello @alterastro,
> 
> I found the problem. It has nothing to do with this pug-loader.
> 
> ### The issue in pug compiler on Windows
> To a filename adds at begin the directory of the source template. For example:
> 
> * source directory: `D:/projects/new-app/src/pages/main/`
> * include a template in pug:
>   ```
>    include D:/projects/new-app/src/layouts/default/default.pug
>   ```
> 
> The pug compiler translate the file `include D:/projects/new-app/src/layouts/default/default.pug` into `include D:/projects/new-app/src/pages/main/D:/projects/new-app/src/layouts/default/default.pug`
> 
> Also, pug compiler do: `source directory` + `included file`.
> 
> ### Why?
> The fixed rule of file naming in pug: an absolute filename **MUST** begin exact with `/`. Otherwise will be added at begin of a filename the `source directory`.
> 
> The concrete place of issue/feature in source code of pug is [in this file, line 78](https://github.com/pugjs/pug/blob/6cca8f76befe7285eead0416ba4e2dbba825ab65/packages/pug-load/index.js#L78):
> 
> ```js
> load.resolve = function resolve(filename, source, options) {
>  // ...
>   filename = path.join(
>     filename[0] === '/' ? options.basedir : path.dirname(source.trim()), // <==== HERE is the problem
>     filename
>   );
> 
>   return filename;
> };
> ```
> 
> ## Solution
> Add to an absolute filename at begin the `/`. For example:
> 
> ```
> alias: {
>   UI: '/D:/projects/UI/src/components',
>   Layouts: '/' + path.resolve('src', 'layouts'),
> },
> ```

Did as in your suggestion, but it didn't help.
Unfortunately, this solution does not help either for UI or Layouts.
I still get concatenated paths (

**Comment by webdiscus** [comment]
Hello. @alterastro,

I have fixed the issues on windows (tested on Win 10), ver. 1.5.1.
Can you please try test it?

**Comment by alterastro** [comment]
> Hello. @alterastro,
> 
> I have fixed the issues on windows (tested on Win 10), ver. 1.5.1. Can you please try test it?

Everything works great now!
Thank you so much for your work!

**Comment by webdiscus** [comment]
Hello @alterastro,

very nice :-)
Then this issue can be closed.
