### ISSUE TITLE
img srcset attribute

### ISSUE THREAD

**Issue by baronkoko** [webdiscus/pug-loader#7]
Hi, is it possible to use such a feature?

```
img(
  src=require('@/assets/images/img.png'),
  srcset=`${require('@/assets/images/img@2x.png')} 2x, ${require('@/assets/images/img@3x.png')} 3x`,
  alt='My image'
)
```

This code currently gives the following error:

`Error: Error parsing body of the with expression`

Stack: 
- "webpack": "^5.66.0";
- "pug": "^3.0.2";
- "@webdiscus/pug-loader": "^1.6.0";
- "html-webpack-plugin": "^5.5.0"

**Comment by baronkoko** [comment]
[Method html](https://github.com/webdiscus/pug-loader#method-html) helped. Everything worked 

```
img(
  src='~@/assets/images/img.png',
  srcset='~@/assets/images/img@2x.png 2x, ~@/assets/images/img@3x.png 3x',
  alt='My image'
)
```

Thank you for your work!

**Comment by webdiscus** [comment]
Hello @baronkoko,

thank you for interesting usage case.
I have implemented the resolving for `srcset` in the new version `1.6.1`.
Now all methods can correct resolve it.
For example:

```pug
 img(srcset=`${require('./image1.jpeg')} 320w, ${require('./image2.jpeg')} 640w` src=require('./image.jpeg'))
```
 output
 ```html
 <img srcset="/assets/image1.f78b30f4.jpeg 320w, /assets/image2.f78b30f4.jpeg 640w" src="/assets/image.f78b30f4.jpeg">
 ```

You can see [the test case](https://github.com/webdiscus/pug-loader/tree/master/test/cases/require-img-srcset).

**Comment by baronkoko** [comment]
@webdiscus Wow, thanks for the quick response and solution!
